# Generated by Django 3.2.5 on 2021-07-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation_tables',
            options={'verbose_name_plural': 'Invitation Table'},
        ),
    ]
