# Generated by Django 3.2.5 on 2021-08-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('active', 'Active')], default='active', max_length=10),
        ),
    ]
