# Generated by Django 3.2.5 on 2021-07-30 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(default='', max_length=250)),
                ('art_code', models.CharField(max_length=7)),
                ('art_volume', models.IntegerField(default=1)),
                ('art_date', models.DateField(auto_now=True)),
                ('art_created_date', models.DateField(auto_now_add=True)),
                ('art_cover', models.ImageField(blank=True, null=True, upload_to='uploads/article_cover/')),
                ('art_document', models.FileField(upload_to='uploads/article_document/')),
                ('ee', models.CharField(max_length=50)),
                ('art_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.categories')),
                ('art_publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
