# Generated by Django 3.2.5 on 2021-07-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='ee',
        ),
    ]
