# Generated by Django 3.2.5 on 2021-07-30 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_remove_articles_ee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='art_publisher',
        ),
        migrations.AddField(
            model_name='articles',
            name='art_publisher',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
