# Generated by Django 3.2.5 on 2021-07-30 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20210730_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='art_publisher',
        ),
        migrations.AddField(
            model_name='articles',
            name='art_publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
