# Generated by Django 3.2.5 on 2021-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articles_art_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='art_description',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
