# Generated by Django 3.2.5 on 2021-08-19 11:53

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articles_art_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='art_code',
            field=models.CharField(default='A896267', max_length=7),
        ),
        migrations.AlterField(
            model_name='articles',
            name='art_cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, size=[570, 480], upload_to='uploads/article_cover/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='art_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/article_document/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='art_title',
            field=models.CharField(max_length=250),
        ),
    ]
