# Generated by Django 3.2.5 on 2021-08-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210819_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='art_code',
            field=models.CharField(default='A472896', max_length=7),
        ),
    ]
