# Generated by Django 3.2.5 on 2021-08-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
